[package]
name = "pyproj"
version = "0.1.0"
edition = "2021"

[dependencies]
dialoguer = "0.12.0"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.5", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
which = "8.0.0"
owo-colors = "4"

